name: Update Data

on:
  workflow_dispatch:
  schedule:
    - cron: "00 00 * * *" # Every day at 00:00

jobs:
  pyScrapers:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name : Checkout Repository
        uses : actions/checkout@v4

      - name : Install Python
        uses : actions/setup-python@v5
        with :
          python-version: "3.12.7"

      - name : Show Python Version
        run  : python -c "import sys; print(sys.version)"

      - name : Install Dependencies
        run  : |
          cd src/scrapers
          python -m pip install --upgrade pip
          pip install -Ur requirements.txt

      - name : Run Code
        run  : |
          python src/scrapers/main_scraper.py

      - name : Repo Update
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update data"
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          file_pattern: "data/raw/anitsayac_data_all_raw.csv"